language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install codecov

script:
  - tox
  - coverage run tests.py
  - coverage report -m

after_success:
  - codecov
